title: Canivete
email: leo@leofavre.com
description: >
  Canivete (portuguese for army knife) is a set of Javascript
  multi-purpose functions; a personal and on-going project
  where I keep functions that I find myself writing over and
  over again.
baseurl: "/canivete"
url: "https://leofavre.github.io"
github_username: leofavre

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - index.js

gems:
  - jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 4 versions